# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, feature-* ]
  pull_request:
    branches: [ master, feature-* ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job for building on each of our supported platforms
  # build-webview-v2:
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest

  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #   # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #   - uses: actions/checkout@v2
  #   # Setup SSH key
  #   - uses: webfactory/ssh-agent@v0.4.1
  #     with:
  #       ssh-private-key: ${{ secrets.SSH_KEY }}

  #   # Install cordova requirements
  #   - name: Install cordova cli
  #     run: sudo npm install -g cordova

  #   - name: Setup Cordova
  #     uses: oxr463/setup-cordova@0.0.1
  #     with:
  #       cordova_exec: cordova -v

  #   # Initiate build
  #   - name: Initiate build
  #     run: |
  #       npm run install-plugins
  #       npm run install-webview-2-5-1
  #       cordova platform add https://github.com/apache/cordova-android.git
  #       cordova build android

  #   # Upload APK
  #   - name: Upload APK
  #     uses: actions/upload-artifact@v1
  #     with:
  #       name: Webview v2.5.1 APK
  #       path: ./platforms/android/app/build/outputs/apk/debug/app-debug.apk

  build-webview-v4:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # v2.3.4
    - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    # Setup SSH key
      # v0.5.0
    - uses: webfactory/ssh-agent@6b2f2c5354ff41f1edbbf7a17ea9b6178c89be9f
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    # Install cordova requirements
    - name: Install cordova cli
      run: sudo npm install -g cordova

    - name: Setup Cordova
      # 0.0.2
      uses: oxr463/setup-cordova@cfd9f1c03c813dddb8a934257f159147bb15bcd4
      with:
        exec: cordova -v

    - name: Install NDK
      run: echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;21.0.6113669" --sdk_root=${ANDROID_SDK_ROOT}

    - name: Install correct JDK
      # 1.1.1
      uses: AdoptOpenJDK/install-jdk@2f15d3f82051aa50984186fc1184467d0d9f87d0
      with:
        version: '1.8'

    # Initiate build
    - name: Initiate build
      run: |
        npm run install-plugins
        npm run install-webview-4-2-1
        cordova platform add android@9.0.0
        cordova build android

    # Upload APK
    - name: Upload APK
      # v2.2.2
      uses: actions/upload-artifact@e448a9b857ee2131e752b06002bf0e093c65e571
      with:
        name: Webview v4.2.1 APK
        path: ./platforms/android/app/build/outputs/apk/debug/app-debug.apk
