# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ splash-screen-autohide ]
  pull_request:
    branches: [ splash-screen-autohide ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job for building on each of our supported platforms
  build-webview-v2:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Setup SSH key
    - uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    # Install cordova requirements
    - name: Install cordova cli
      run: sudo npm install -g cordova

    - name: Setup Cordova
      uses: oxr463/setup-cordova@0.0.1
      with:
        cordova_exec: cordova -v

    # Initiate build
    - name: Initiate build
      run: |
        npm run install-plugins
        npm run install-webview-2-5-1
        cordova platform add android@latest
        cordova build android

    # Upload APK
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: Webview v2.5.1 APK
        path: ./platforms/android/app/build/outputs/apk/debug/app-debug.apk

  build-webview-v4:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Setup SSH key
    - uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    # Install cordova requirements
    - name: Install cordova cli
      run: sudo npm install -g cordova

    - name: Setup Cordova
      uses: oxr463/setup-cordova@0.0.1
      with:
        cordova_exec: cordova -v

    # Initiate build
    - name: Initiate build
      run: |
        npm run install-plugins
        npm run install-webview-4-2-1
        cordova platform add android@latest
        cordova build android

    # Upload APK
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: Webview v4.2.1 APK
        path: ./platforms/android/app/build/outputs/apk/debug/app-debug.apk
